name: FactionUI
main: FactionUI\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA12, 3.0.0, 3.1.0, 3.2.0, 3.3.0]
version: 1.0.0
author: BajanVlogs

commands:
 repairui:
  description: "This is for Faction servers using CustomUI"
